wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename} Recovery"

captive_portal:

web_server:
  port: 80
  ota: true

# Enable logging
logger:
  level: INFO
  id: logginglevel
# Enable Home Assistant API
api:
  password: !secret api_password
  
# Secure OTA
ota:
